### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sykursen** [aristocratos/bpytop#121]
**Describe the bug**

The app just crash

**To Reproduce**

Launch bpytop, set timer to 500ms and after severals minutes, bpytop crash

**Info (please complete the following information):**
- bpytop version: 1.0.32
- psutil version: 5.7.2
- Linux Mint 20 Ulyana
- Zsh shell in mate terminal
- Python 3.8.2

**Additional context**
`14/09/20 (20:35:56) | ERROR: Data collection thread failed with exception: 'NoneType' object has no attribute 'percent'
Traceback (most recent call last):
  File "/home/guillaume/.local/lib/python3.8/site-packages/bpytop.py", line 2497, in _runner collector._draw()
  File "/home/guillaume/.local/lib/python3.8/site-packages/bpytop.py", line 2722, in _draw CpuBox._draw_fg()
  File "/home/guillaume/.local/lib/python3.8/site-packages/bpytop.py", line 1627, in _draw_fg cls.battery_percent = ceil(psutil.sensors_battery().percent)
AttributeError: 'NoneType' object has no attribute 'percent'
14/09/20 (20:35:56) | WARNING: Exiting with errorcode (1). Runtime 0:09:11`
![image](https://user-images.githubusercontent.com/18405490/93137156-8e564080-f6cc-11ea-8ece-0ccefd2757d9.png)

**Comment by aristocratos** [comment]
Should be fixed in v1.0.33

**Comment by Sykursen** [comment]
Nice, the program now work smoothly again 🙌
