### ISSUE TITLE
MacOS launch failure after upgrade to 1.0.39

### ISSUE THREAD

**Issue by denningsrogue** [aristocratos/bpytop#136]
After updating to bpytop version 1.0.39 (psutil version: 5.7.2), I get the following error when launching bpytop.

"Bpytop exited with errorcode (1). See /Users/denningsrogue/.config/bpytop/error.log for more information!"

I am using:
- MacOS 10.15.7
- Python 3.8.5
- iTerm 3.3.12

Here is the output in the log:

28/09/20 (08:21:34) | ERROR: Data collection thread failed with exception: [Errno 2] No such file or directory: '/sys/class/power_supply'
Traceback (most recent call last):
  File "/Users/denningsrogue/.pyenv/versions/3.8.5/lib/python3.8/site-packages/bpytop.py", line 2581, in _runner
    collector._draw()
  File "/Users/denningsrogue/.pyenv/versions/3.8.5/lib/python3.8/site-packages/bpytop.py", line 2817, in _draw
    CpuBox._draw_fg()
  File "/Users/denningsrogue/.pyenv/versions/3.8.5/lib/python3.8/site-packages/bpytop.py", line 1704, in _draw_fg
    if CONFIG.show_battery and cls.battery_activity():
  File "/Users/denningsrogue/.pyenv/versions/3.8.5/lib/python3.8/site-packages/bpytop.py", line 1640, in battery_activity
    for directory in os.listdir("/sys/class/power_supply"):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'
28/09/20 (08:21:35) | WARNING: Exiting with errorcode (1). Runtime 0:00:03

**Comment by aristocratos** [comment]
@denningsrogue 
This was fixed a couple of minutes ago in v1.0.40
See https://github.com/aristocratos/bpytop/issues/134 for more info.
