### ISSUE TITLE
[BUG] Crashes on Termux/Android

### ISSUE THREAD

**Issue by blmvxer** [aristocratos/bpytop#144]
So I see the issue is with permissions

PermissionError: [Errno 13] Permission denied: '/proc/stat'

I can try working on a termux friendly approach here in a couple days.

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_common.py", line 405, in wrapper                                                                        return cache[key]                                                                   KeyError: (('/proc',), frozenset())                                                                                                                                             During handling of the above exception, another exception occurred:
                                                                                        Traceback (most recent call last):                                                        File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_pslinux.py", line 309, in <module>                                                                      set_scputimes_ntuple("/proc")                                                         File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_common.py", line 407, in wrapper                                                                        ret = cache[key] = fun(*args, **kwargs)                                               File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple                                                          with open_binary('%s/stat' % procfs_path) as f:                                       File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)                                                  PermissionError: [Errno 13] Permission denied: '/proc/stat'
Bpytop exited with errorcode (1). See /data/data/com.termux/files/home/.config/bpytop/error.log for more information!

**Comment by aristocratos** [comment]
@blmvxer 
Not sure why this is labeled a bug, I've never claimed BpyTOP have support for Android.

> I can try working on a termux friendly approach here in a couple days.

I think this is a bigger headache then you assume. First you would need to adapt [psutil](https://github.com/giampaolo/psutil) to work under Android.

**Comment by aristocratos** [comment]
>  PermissionError: [Errno 13] Permission denied: '/proc/stat'

Seems you would also need a rooted Android device to get past the permission errors.

**Comment by TheComputerGuy96** [comment]
![](https://i.imgur.com/gniIlk9.png)

**Comment by J053Fabi0** [comment]
> ![](https://camo.githubusercontent.com/63318ce8bbc87392590865bd8f2134ff57b30ef9f39e3d4932054268daebc75b/68747470733a2f2f692e696d6775722e636f6d2f676e69496c6b392e706e67)

Andn how did you do that?

**Comment by TheComputerGuy96** [comment]
> And how did you do that?

@J053Fabi0 I think it was as easy as installing it with `pip3` and then running it with `tsu` (which requires root access)
