### ISSUE TITLE
[BUG] Crashed with mouse click and drag

### ISSUE THREAD

**Issue by nifisher** [aristocratos/bpytop#147]
**Describe the bug**

bpytop running in a tmux pane.   Runs fine, but when mouse is clicked and dragged it crashes with error

**To Reproduce**

tmux config at end of bug report as i don't know what setting might be important.
Launch tmux
Launch bpytop
wait for it to load
click in window and drag mouse while holding button down

**Expected behavior**

not crash.
beyond that i didn't know what it would do.

**Screenshots**

```
[pandora (2.0)]:: bash --version
GNU bash, version 5.0.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[pandora (2.0)]:: tmux -V
tmux 3.1b

[pandora (2.0)]:: python -V
Python 3.8.6


[pandora (2.0)]:: bpytop -v
bpytop version: 1.0.42
psutil version: 5.7.2


[pandora (2.0)]:: bpytop 
Bpytop exited with errorcode (1). See /home/nifisher/.config/bpytop/error.log for more information!


[pandora (2.0)]:: @^@_@_@`@`@a@b@c@d@d@e@f@f@g@g@h@h@i@j@k@k@l@m@n@n@o@p@q@r@s@t@u@v@w@x@y@z@{@|@}@~@@@@@@@@@@@@@@    <----------- this I expect is what was being sent to bpytop that it couldn't figure out how to handle.  it was in the prompt when it crashed.  CTRL-C (removed) moved me off this line


[pandora (2.0)]:: cat /home/nifisher/.config/bpytop/error.log
16/10/20 (12:04:56) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x96 in position 5: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 5: invalid start byte
16/10/20 (12:04:56) | WARNING: Exiting with errorcode (1). Runtime 1:33:19 

16/10/20 (12:06:09) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte
16/10/20 (12:06:11) | WARNING: Exiting with errorcode (1). Runtime 0:00:07 

16/10/20 (12:08:12) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x8b in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 4: invalid start byte
16/10/20 (12:08:12) | WARNING: Exiting with errorcode (1). Runtime 0:00:09 
```

**Info (please complete the following information):**
 - bpytop version: `bpytop -v` 1.0.42
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) 5.7.2
 - (Linux) Linux distribution and version: Arch/x86_64, current version
 - (OSX/FreeBSD) Os release version: n/a
 - Terminal used: bash
 - Font used: -windows-montecarlo-medium-r-normal-*-11-110-*-*-*-*-*-*
 - Python version, `python3 --version` (version 3.6 or above is required): 3.8.6

**Additional context**
see screenshot section for bpytop error log

tmux cfg:
```
# caa << EOF > /dev/null

# -- general -------------------------------------------------------------------

#set -g default-terminal "screen-256color" # colors!
setw -g xterm-keys on
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on

#set -g prefix2 C-a                        # GNU-Screen compatible prefix
#bind C-a send-prefix -2

set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on

#set -g history-limit 5000                 # boost history

# edit configuration
bind e new-window -n '~/.tmux.conf' "sh -c '\${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# -- display -------------------------------------------------------------------

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g set-titles on          # set terminal title

set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

set -g status-interval 10     # redraw status line every 10 seconds

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.1' \; clear-history

# -- navigation ----------------------------------------------------------------

# create session
bind C-c new-session

# find session
bind C-f command-prompt -p find-session 'switch-client -t %%'

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


#-- design changes -------------------------------------------------------------

# loud or quiet?
set-option -g visual-activity on
set-option -g visual-bell on
set-option -g visual-silence off
set-window-option -g monitor-activity on
set-option -g bell-action none

#  modes
setw -g clock-mode-colour colour5

# statusbar
set -g status-position bottom
set -g status-justify left


set -g status on

# Turn on terminmal window titles
set -g set-titles on

# Set terminal window title string
#  #H  Hostname of local host
#  #I  Current window index
#  #P  Current pane index
#  #S  Session name
#  #T  Current window title
#  #W  Current window name
#  #   A literal ‘#’
set -g set-titles-string '#S:#I.#P #W'


# set pane titles
# set pane title with: printf '\033]2;%s\033\\' 'title goes here'
#set -g pane-border-status top
#set -g pane-border-status bottom

# Automatically set window title
set -g automatic-rename-format "#{s/bash//:pane_current_command}"


# Misc settings
set -g default-terminal "screen-256color"

# Scroll History
set -g history-limit 30000

# Visual notifcation of window activity
setw -g monitor-activity on
set -g visual-activity on

# programs like vim will use an alternate screen buffer (tidier i think)
set-window-option -g alternate-screen on

# new way
set -g mouse on
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 20
set -g status-right '#(eval .tmux/scripts/status.sh `tmux display -p "#{client_width}"`)'
set -g status-left '#[fg=colour16,bg=colour254,bold] #T #[fg=colour254,bg=colour234,nobold] '

set -g status-right-length 150

set -g window-status-format         "#[fg=colour244,bg=colour234]#I.#{?#{==:#{host},#{pane_title}},#P,#T}:#[fg=colour240] #{=-15:?window_name,#{window_name},#{s/nifisher/home/:?pane_current_path,#{b:pane_current_path},}}#F "
set -g window-status-current-format "#[fg=colour117 bold, bg=colour32]#I#[fg=colour117 nobold, bg=colour32].#{?#{==:#{host},#{pane_title}},#P,#T}:#[fg=colour231 bold, bg=colour31] #{=-15:?window_name,#{window_name},#{s/nifisher/home/:?pane_current_path,#{b:pane_current_path},}}#F #[fg=colour31,bg=colour234,nobold] "


# edit configuration
bind e new-window -n '~/.tmux.conf' "sh -c '\${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'


# window navigation
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Space last-window      # move to last active window
```

**Comment by nifisher** [comment]
definitely something to do with how TMUX handles click and drag as it doesn't crash when run in a terminal directly.   In old versions the option was labeled "copy mode" or something and was set to handle mouse scrolling, but I don't see that in my current config

**Comment by aristocratos** [comment]
@nifisher 
This seems to be a tmux problem since python itself can't decode the codes returned from the mouse actions as utf-8.
The mouse reporting is enabled with the escape codes `\033[?1002h`, `\033[?1015h` and `\033[?1006h` for best compatibility, but in your case it looks like the standard isn't being followed since: `@^@_@_@`@`@a@b@c@d@d@e@f@f@g@g@h@h@i@j@k@k@l@m@n@n@o@p@q@r@s@t@u@v@w@x@y@z@{@|@}@~@@@@@@@@@@@@@@` isn't what's supposed to be reported by the terminal.

But I don't now if I see this as a very serious issue since mouse dragging isn't used for anything in bpytop anyways.

**Comment by nifisher** [comment]
Purposeful click/drag may not do anything.
As I just accidentally click/draged when I selected that window with a long, slow click however....

Either way, crashing is not really ideal.  I haven't looked at the code yet, but shouldn't this be a relatively minor try/catch for exception from codecs.py?

**Comment by aristocratos** [comment]
I can't replicate the issue in tmux 3.0a, mouse works as expected.

> Terminal used: bash

Which terminal emulator are you using?

**Comment by nifisher** [comment]
yeah, bash isn't what you'd want there..  sorry about that
rxvt-unicode-minimal 9.22-11


And double checking things, the option that I was remembering is [copy mode in TMUX](http://www.rushiagr.com/blog/2016/06/16/everything-you-need-to-know-about-tmux-copy-pasting-ubuntu/#:~:text=Tmux%20copy-paste%20-%20the%20defaults%201%20Enter%20%E2%80%98copy,to%20paste%20in%20a%20possibly%20different%20Tmux%20pane%2Fwindow.).  Copying manually with the keyboard works fine.  Entering copymode and selecting with the mouse works fine as well (though since we are in copymode it shouldn't be sending anything to the terminal)

Something that I didn't think to check at all before, `htop` ignores click/drag entirely and TMUX doesn't enter copymode.   The scroll wheel does scroll the process list however (which i expected).

Trying the scroll wheel in bpytop, it does nothing (wasn't surprised by this, but hoped it would scroll the process list), but it did end up crashing.   So however TMUX mouse support enters copymode causes problems for python it seems

```[pandora (2.0)]:: bpytop 
Bpytop exited with errorcode (1). See /home/nifisher/.config/bpytop/error.log for more information!


[pandora (2.0)]:: ``aaaa```aaaa````aaaa````aaaa```aaa^C

[pandora (2.0)]:: cat /home/nifisher/.config/bpytop/error.log
16/10/20 (12:04:56) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x96 in position 5: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 5: invalid start byte
16/10/20 (12:04:56) | WARNING: Exiting with errorcode (1). Runtime 1:33:19 

16/10/20 (12:06:09) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte
16/10/20 (12:06:11) | WARNING: Exiting with errorcode (1). Runtime 0:00:07 

16/10/20 (12:08:12) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x8b in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 4: invalid start byte
16/10/20 (12:08:12) | WARNING: Exiting with errorcode (1). Runtime 0:00:09 

16/10/20 (12:54:02) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0xc1 in position 5: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 5: invalid start byte
16/10/20 (12:54:03) | WARNING: Exiting with errorcode (1). Runtime 0:35:21 

16/10/20 (13:18:43) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0xad in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 4: invalid start byte
16/10/20 (13:18:43) | WARNING: Exiting with errorcode (1). Runtime 0:24:30 

16/10/20 (13:22:12) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x88 in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 822, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 4: invalid start byte
16/10/20 (13:22:14) | WARNING: Exiting with errorcode (1). Runtime 0:00:07 
```

**Comment by aristocratos** [comment]
>  but shouldn't this be a relatively minor try/catch for exception from codecs.py?

That would be a very last resort fix since that try block would have to cover all input read and if there were to be a continuous stream of non utf-8 characters sent to the terminal (by this issue or any other possible issue) the program would become unresponsive by locking up the input thread. So I would rather have the program crash out and write to log to properly diagnose other input related issues.

But however, this issue isn't actually happening in the bpytop code, but part of the python3 standard library [codec.py](https://docs.python.org/3/library/codecs.html).

The chain of events could possibly be something along the lines of:
1. Start tmux
2. Enable mouse reporting `echo -e "\033[?1002h\033[?1015h\033[?1006h"`
3. Enter mouse copy mode
4. tmux starts sending non utf-8 formatted characters to stdin

**Comment by nifisher** [comment]
```[pandora (2.0)]:: echo -e "\033[?1002h\033[?1015h\033[?1006h"


[nifisher@~]
[pandora (2.0)]:: `K`K`KaBaBaBaBaB`C`B`B`B`BaBaBaBaBaB`B`B`B`B`BaBaBaBaBaB`A`>`=`=`=a=a=a=a=a=a=`=`=`<`<`<`<a<a<a<a<a<a<`<`<`<`<`<a<a<a<a<`<`<`<`<a<a<a<a<`< <@<@=@>@>@?@?@?@?@?@?@?@?@?@?@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@>@?@?@@@A@A@B@B@C@C@D@D@E@E@F@F@F@G@G@G@H@H@H@I@I@I@I@I@I@I@I@H@H@G@G@F@F@E@E@D@D@C@C@B@B@A@@@@@?@?@>@>@?@@@@@A@B@B@C@E@F@G@G@H@H@I@I@J@J@K@K@L@L@M@L@L@K@K@J@J@I@I@H@H@H@G@G@G@H@I@J@J@K@K@L@L@M@M@N@N@O@O@P@P@Q@Q@R@R@S@S@T@T@T@T@S@S@R@R@Q@Q@R@S@T@U@V@W@X@X@Y@Z@[@[@\@\@]@^@_@_@`@a@b@b@c@c@d@d@e@e@f@f@e@d@c@b@a@`@_@_@^@]@\@\@[@[@Z@Y@X@X@W@V@U@U@T@T@S@R@R@Q@Q@P@Q@Q@R@S@T@U@U@V@W@X@Y@Z@Z@Y@Y@X@W@V@V@U@T@T@U@U@V@W@X@X@Y@Z@[@[@\@]@]@^@_@`@`@a@`@`@_@^@]@\@\@[@Z@Z@Y@Z@[@[@\@]@^@^@_@`@_@_@^@^@]@\@\@\@]@^@]@\@\@[@\@]@]@^@_@`@a@a@b@b@c@d@c@c@b@b@a@a@`@_@_@^@^@]@\@\@[@\@\@]@]@^@_@`@`@a@a@b@a@`#`a]a]a]a]a]`\`[`Z`ZaZaZaZaZ`Z`W`W`W`VaVaVaVaVaV`V`V`V`VaVaVaVaV`V`U`U`UaUaUaUaU`U`S`RaRaRaR`R`R`RaRaRaR`R`R`RaRaRaRaBaBaB`BaB
```

Seems likely

**Comment by nifisher** [comment]
And when not under tmux:
```
[pandora (2.0)]:: echo -e "\033[?1002h\033[?1015h\033[?1006h"

[pandora (2.0)]:: 6;36;18M7;15;16M7;15;16M7;15;16M6;15;
```

**Comment by aristocratos** [comment]
Have you tested if this happens with latest version from https://github.com/tmux/tmux ?

If that's the case, I would suggest you report this issue to them.

**Comment by nifisher** [comment]
3.1b is the latest release, unless you are suggesting the nightly

when you tested in tmux, did you have unicode enabled or no?

**Comment by aristocratos** [comment]
I have no custom tmux.conf and I would assume the default settings have unicode on by default since all nerdfont symbols in my zsh prompt shows up correctly.

I just found this which seems to have some relevance https://github.com/tmux/tmux/issues/209
