### ISSUE TITLE
[BUG] Error: Permission denifed: '/proc/partitions'

### ISSUE THREAD

**Issue by GalGreenfield** [aristocratos/bpytop#17]
**Describe the bug**

[A clear and concise description of what the bug is.]

I'm getting the error: `permission denied: '/proc/partitions'`
Full error:
> 04/08/20 (16:36:52) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2313, in _runner
    collector._collect()
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2579, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
04/08/20 (16:36:52) | WARNING: Exiting with errorcode (1). Runtime 0:00:03

**To Reproduce**

1. Install `bpytop` by running: `sudo snap install bpytop`
2. In a terminal, launch `bpytop` with `bpytop`.
3. It will start running, and then crash at the stage that's *one after* data collection and drawer something (it's too fast for me to see and the error log doesn't say at which staged it crashed).
*Note: The error is logged in the log file at: `/snap/bpytop/26/.config/bpytop/error.log` (for me, at least)

**Expected behavior**

For the application to finish booting up properly.

**Info (please complete the following information):**
 - bpytop version: 1.0.1
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) - 5.4.2, even though I installed on my system v5.7.2 (latest at the time of writing this)
 - (Linux) Linux distribution and version:
 - (OSX/FreeBSD) Os release version: Kubuntu 20.04
 - Terminal used: Konsole
 - Font used: FiraCode Nerd Font
 - Python version, `python3 --version` (version 3.6 or above is required): 3.8.2

**Additional context**

contents of `~/.config/bpytop/error.log` (installed bpytop via snap so the error log's path for me is `~/snap/bpytop/26/.config/bpytop/error.log`):
```
04/08/20 (16:36:52) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2313, in _runner
    collector._collect()
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2579, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
04/08/20 (16:36:52) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 

04/08/20 (16:37:00) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2313, in _runner
    collector._collect()
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2579, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
04/08/20 (16:37:00) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 

04/08/20 (16:48:27) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2313, in _runner
    collector._collect()
  File "/snap/bpytop/26/usr/local/bin/bpytop", line 2579, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/26/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
04/08/20 (16:48:27) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 
```

**Comment by aristocratos** [comment]
I'm not the maintainer for the snap package.

See https://github.com/kz6fittycent/bpytop-snap

But I'm gonna guess you didn't run the `snap connect` commands to give bpytop permissions?

**Comment by GalGreenfield** [comment]
> I'm not the maintainer for the snap package.
> 
> See https://snapcraft.io/bpytop or https://github.com/kz6fittycent/bpytop-snap
> 
> But I'm gonna guess you didn't run the `snap connect` commands to give bpytop permissions?

I wasn't even aware of needing to do `snap connect` and didn't even think to check the snap package - I thought it's shipped by you. That solved it - thanks for the help! :)

**Comment by slmingol** [comment]
Just in case anyone stumbles here, this page shows how to do the connects - https://snapcraft.io/bpytop.

```
sudo snap connect bpytop:mount-observe
sudo snap connect bpytop:network-control
sudo snap connect bpytop:hardware-observe
sudo snap connect bpytop:system-observe
sudo snap connect bpytop:process-control
sudo snap connect bpytop:physical-memory-observe
```
