### ISSUE TITLE
[Errno 13] SNAP:  Permission denied: '/proc/diskstats'[BUG] 

### ISSUE THREAD

**Issue by cavazquez** [aristocratos/bpytop#174]
**Describe the bug**

Error when execute bpytop

**To Reproduce**

[Steps to reproduce the behavior:]

run: bpytop in bash

[A clear and concise description of what you expected to happen.]

29/10/20 (00:12:45) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
Traceback (most recent call last):
  File "/snap/bpytop/152/usr/bin/bpytop", line 2598, in _runner
    collector._collect()
  File "/snap/bpytop/152/usr/bin/bpytop", line 2956, in _collect
    io_counters = psutil.disk_io_counters(perdisk=SYSTEM == "Linux", nowrap=True)
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/__init__.py", line 2041, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1119, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1070, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_common.py", line 724, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
29/10/20 (00:12:45) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
bpytop version: 1.0.47
psutil version: 5.7.3
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Bash
 - Font used:
 - Python version, 3.8

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by cavazquez** [comment]
ohh sorry. with snap connect its works.
