### ISSUE TITLE
[BUG ][Errno 13] Permission denied: '/proc/diskstats'

### ISSUE THREAD

**Issue by ubuntupunk** [aristocratos/bpytop#181]
**Describe the bug**

Snap Fails on Ubuntu 20.04

Traceback (most recent call last):
  File "/snap/bpytop/152/usr/bin/bpytop", line 2598, in _runner
    collector._collect()
  File "/snap/bpytop/152/usr/bin/bpytop", line 2956, in _collect
    io_counters = psutil.disk_io_counters(perdisk=SYSTEM == "Linux", nowrap=True)
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/__init__.py", line 2041, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1119, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1070, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_common.py", line 724, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'

**To Reproduce**

run app in terminal for first time

**Expected behavior**

Request elevated privileges or configuration

app crashes

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`

 - psutil version: `bpytop -v` (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version:
 - (OSX/FreeBSD) Os release version:
 - Terminal used: gnome-terminal
 - Font used: 
 - Python version, `python3 --version` (version 3.6 or above is required):

**Additional context**

bpytop version: 1.0.47
psutil version: 5.7.3

contents of `~/.config/bpytop/error.log`

31/10/20 (23:30:03) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
Traceback (most recent call last):
  File "/snap/bpytop/152/usr/bin/bpytop", line 2598, in _runner
    collector._collect()
  File "/snap/bpytop/152/usr/bin/bpytop", line 2956, in _collect
    io_counters = psutil.disk_io_counters(perdisk=SYSTEM == "Linux", nowrap=True)
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/__init__.py", line 2041, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1119, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1070, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/152/usr/lib/python3/dist-packages/psutil/_common.py", line 724, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
31/10/20 (23:30:03) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

31/10/20 (23:33:03) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'

**Comment by aristocratos** [comment]
@ubuntupunk 
Read the instructions
https://github.com/aristocratos/bpytop#snap-package
https://github.com/kz6fittycent/bpytop-snap
https://snapcraft.io/bpytop

**Comment by ubuntupunk** [comment]
Thanks. Error log should suggest the snap connects.
