### ISSUE TITLE
[BUG] Crash on ARM MacOS

### ISSUE THREAD

**Issue by morozsm** [aristocratos/bpytop#203]
Crashes when run on MacOS 11 on Apple Silicone ARM CPU

[Steps to reproduce the behavior:]

Run application on Big Sur on Apple ARM computer

**Expected behavior**

Normal execution

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: 1.0.50
 - psutil version: 5.7.3
 - (OSX/FreeBSD) Os release version: Big Sur on ARM
 - Terminal used: Terminal.app, iTerm2
 - Font used: Hack NF
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.9.0

**Additional context**

22/11/20 (23:55:26) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 2599, in _runner
    collector._collect()
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 3259, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1414, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 523, in as_dict
    ret = meth()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 675, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
22/11/20 (23:55:26) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

22/11/20 (23:55:34) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 2599, in _runner
    collector._collect()
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 3259, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1414, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 523, in as_dict
    ret = meth()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 622, in name
    cmdline = self.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 675, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
22/11/20 (23:55:34) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

22/11/20 (23:55:46) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 2599, in _runner
    collector._collect()
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 3259, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1414, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 523, in as_dict
    ret = meth()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 622, in name
    cmdline = self.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 675, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
22/11/20 (23:55:46) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

24/11/20 (12:07:09) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 2599, in _runner
    collector._collect()
  File "/opt/homebrew/lib/python3.9/site-packages/bpytop.py", line 3259, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 1414, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 523, in as_dict
    ret = meth()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 675, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
24/11/20 (12:07:09) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

**Comment by aristocratos** [comment]
@morozsm 
This seems to be an issue with `psutil` on apple arm architecture. I would suggest you clone https://github.com/giampaolo/psutil , run the tests and submit a bug report on the psutil github page.

**Comment by morozsm** [comment]
@aristocratos Thank you, will check.
Actually, have issues on Big Sur on x86_64 also. Will file separate bug report.
That's funny terminal artifacts there...

**Comment by morozsm** [comment]
Ok, with psutil from git repo it started, however, getting 100% the same issue as I've got on Intel Big Sur. See the screenshot:
<img width="1337" alt="Screen Shot 2020-11-24 at 4 59 48 PM" src="https://user-images.githubusercontent.com/4393731/100156205-835f1f80-2e76-11eb-932f-fbda6c1000f4.png">

**Comment by aristocratos** [comment]
@morozsm 
From readme:
> Mac Os X
Will not display correctly in the standard terminal! Recommended alternative iTerm2

**Comment by morozsm** [comment]
whops.. My fault.
