### ISSUE TITLE
[BUG]Real time disk speed monitoring not working

### ISSUE THREAD

**Issue by qiujiangkun** [aristocratos/bpytop#210]
**Is your feature request related to a problem? Please describe.**
I have seen this feature from Windows XP and some other monitor software.  Currently, the disk usage is not helpful since disk capacity does not change very fast.

**Describe the solution you'd like**
You can see the reading and writing rate for each disk. Some software supports individual statistics for each process.
Simply add a row in the disk section like `R: 250MiB/s W:35MiB/s`

**Comment by aristocratos** [comment]
@qiujiangkun 
> I have seen this feature from Windows XP and some other monitor software.

I'm not sure what you're on about. Disk read and write monitoring has been in bpytop since version 1.0.0

**Comment by qiujiangkun** [comment]
Yea, I read it in the feature list. But I haven't seen how to enable it anyway. 
Also, can I set the disk names?
![image](https://user-images.githubusercontent.com/33482468/101894993-e45e5580-3be1-11eb-8847-fb670e9ed531.png)

**Comment by aristocratos** [comment]
@qiujiangkun 
It shows up to the right of the disk name as shown in the screenshot:
https://raw.githubusercontent.com/aristocratos/bpytop/master/Imgs/main.png

If you installed through `snap`, this is likely the issue for both why your disk name is wrong and why you can't see the speed, since it's sandboxed when running as a snap.

Try installing with `pip3` or through distribution package or manually if it's not available for your linux distro.
Should likely solve your issues.

**Comment by qiujiangkun** [comment]
I installed with `pacman -S bpytop` on Manjaro Linux
`community/bpytop 1.0.50-1 [installed]`
There were no warnings or errors while installing.
Am I missing some dependencies?

**Comment by aristocratos** [comment]
@qiujiangkun 
> Am I missing some dependencies?

The only dependency is `psutil` and without it bpytop wouldn't start at all.

Can you run the following commands and post the output?
`python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_partitions(all=False))"`
`python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_io_counters(perdisk=True))"`

**Comment by qiujiangkun** [comment]
```
➜  ~ python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_partitions(all=False))"
[sdiskpart(device='/dev/nvme0n1p3', mountpoint='/', fstype='ext4', opts='rw,noatime'),
 sdiskpart(device='/dev/sda2', mountpoint='/hhd', fstype='ext4', opts='rw,noatime'),
 sdiskpart(device='/dev/sda2', mountpoint='/home', fstype='ext4', opts='rw,noatime'),
 sdiskpart(device='/dev/sda2', mountpoint='/opt', fstype='ext4', opts='rw,noatime'),
 sdiskpart(device='/dev/nvme0n1p1', mountpoint='/boot/efi', fstype='vfat', opts='rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro'),
 sdiskpart(device='/dev/nvme0n1p3', mountpoint='/home/jack/Dev', fstype='ext4', opts='rw,noatime'),
 sdiskpart(device='/dev/nvme0n1p3', mountpoint='/hhd/home/jack/Dev', fstype='ext4', opts='rw,noatime'),
 sdiskpart(device='/dev/sda3', mountpoint='/run/media/jack/Data', fstype='fuseblk', opts='rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096')]
➜  ~ python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_io_counters(perdisk=True))"


{'loop0': sdiskio(read_count=10, write_count=0, read_bytes=10240, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=4),
 'loop1': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop2': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop3': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop4': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop5': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop6': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop7': sdiskio(read_count=0, write_count=0, read_bytes=0, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'nvme0n1': sdiskio(read_count=48555, write_count=8171, read_bytes=1903783936, write_bytes=637592576, read_time=6532, write_time=2607, read_merged_count=49725, write_merged_count=3351, busy_time=25684),
 'nvme0n1p1': sdiskio(read_count=604, write_count=2, read_bytes=5591040, write_bytes=1024, read_time=197, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=80),
 'nvme0n1p2': sdiskio(read_count=57, write_count=0, read_bytes=2260992, write_bytes=0, read_time=1, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=10),
 'nvme0n1p3': sdiskio(read_count=47758, write_count=7979, read_bytes=1892230144, write_bytes=637591552, read_time=6322, write_time=2584, read_merged_count=49725, write_merged_count=3351, busy_time=25674),
 'nvme0n1p4': sdiskio(read_count=83, write_count=0, read_bytes=2415616, write_bytes=0, read_time=7, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=24),
 'sda': sdiskio(read_count=482748, write_count=38993, read_bytes=4333143552, write_bytes=1582223360, read_time=1716901, write_time=413778, read_merged_count=221733, write_merged_count=190879, busy_time=1157827),
 'sda1': sdiskio(read_count=65, write_count=0, read_bytes=2293760, write_bytes=0, read_time=323, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=347),
 'sda2': sdiskio(read_count=476806, write_count=36775, read_bytes=3642115072, write_bytes=965124096, read_time=1684809, write_time=340792, read_merged_count=221723, write_merged_count=41201, busy_time=1119194),
 'sda3': sdiskio(read_count=5780, write_count=981, read_bytes=687517696, write_bytes=617099264, read_time=30283, write_time=38052, read_merged_count=10, write_merged_count=149678, busy_time=29800),
 'sr0': sdiskio(read_count=10, write_count=0, read_bytes=2048, write_bytes=0, read_time=60, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=77)}
➜  ~ bpytop -v
bpytop version: 1.0.50
psutil version: 5.7.3

➜  ~ screenfetch
 ██████████████████  ████████     jack@jack-pc
 ██████████████████  ████████     OS: Manjaro 20.2 Nibia
 ██████████████████  ████████     Kernel: x86_64 Linux 5.8.18-1-MANJARO
 ██████████████████  ████████     Uptime: 1h 1m
 ████████            ████████     Packages: 1881
 ████████  ████████  ████████     Shell: zsh 5.8
 ████████  ████████  ████████     Resolution: 3840x2160
 ████████  ████████  ████████     DE: Xfce4
 ████████  ████████  ████████     WM: Xfwm4
 ████████  ████████  ████████     WM Theme: Matcha-sea
 ████████  ████████  ████████     GTK Theme: Matcha-sea [GTK2]
 ████████  ████████  ████████     Icon Theme: Papirus-Maia
 ████████  ████████  ████████     Font: Noto Sans 12
 ████████  ████████  ████████     Disk: 802G / 6.6T (12%)
                                  CPU: AMD Ryzen 7 3700X 8-Core @ 16x 3.6GHz
                                  GPU: GeForce GTX 1660
                                  RAM: 3682MiB / 16019MiB

➜  ~ cat .config/bpytop/error.log
21/10/20 (14:34:15) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
25/10/20 (11:36:26) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
17/12/20 (21:11:42) | INFO: New instance of bpytop version 1.0.50 started with pid 12700
17/12/20 (21:11:42) | INFO: Loglevel set to DEBUG
17/12/20 (21:11:42) | DEBUG: Using psutil version 5.7.3
17/12/20 (21:11:42) | DEBUG: CMD: /usr/bin/bpytop --debug
17/12/20 (21:11:42) | DEBUG: Collect and draw completed in 0.007652 seconds
17/12/20 (21:11:42) | DEBUG: Init completed in 0.014276 seconds
17/12/20 (21:11:46) | INFO: Exiting. Runtime 0:00:05 
```

**Comment by aristocratos** [comment]
@qiujiangkun 
Made some changes in v1.0.51, let me know if helped.

**Comment by qiujiangkun** [comment]
Sorry that I have been in another city, away from my original devices. I can only report it in a few months

**Comment by qiujiangkun** [comment]
Nothing has been changed except for the version
```log
$ bpytop --version
bpytop version: 1.0.59
psutil version: 5.8.0
$ python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_partitions(all=False))"
[sdiskpart(device='/dev/nvme0n1p3', mountpoint='/', fstype='ext4', opts='rw,noatime', maxfile=255, maxpath=4096),
 sdiskpart(device='/dev/nvme0n1p1', mountpoint='/boot/efi', fstype='vfat', opts='rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro', maxfile=1530, maxpath=4096),
 sdiskpart(device='/dev/sda2', mountpoint='/hdd', fstype='ext4', opts='rw,noatime', maxfile=255, maxpath=4096),
 sdiskpart(device='/dev/sda2', mountpoint='/home', fstype='ext4', opts='rw,noatime', maxfile=255, maxpath=4096),
 sdiskpart(device='/dev/sda2', mountpoint='/opt', fstype='ext4', opts='rw,noatime', maxfile=255, maxpath=4096),
 sdiskpart(device='/dev/nvme0n1p3', mountpoint='/home/jack/Dev', fstype='ext4', opts='rw,noatime', maxfile=255, maxpath=4096),
 sdiskpart(device='/dev/nvme0n1p3', mountpoint='/hdd/home/jack/Dev', fstype='ext4', opts='rw,noatime', maxfile=255, maxpath=4096)]
$  python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_io_counters(perdisk=True))"
{'loop0': sdiskio(read_count=11, write_count=0, read_bytes=14336, write_bytes=0, read_time=0, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=10),
 'nvme0n1': sdiskio(read_count=4196557, write_count=747635, read_bytes=155749294592, write_bytes=91739935744, read_time=966919, write_time=4211274, read_merged_count=807871, write_merged_count=527722, busy_time=971774),
 'nvme0n1p1': sdiskio(read_count=1407, write_count=2, read_bytes=6017536, write_bytes=1024, read_time=216, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=110),
 'nvme0n1p2': sdiskio(read_count=57, write_count=0, read_bytes=2260992, write_bytes=0, read_time=1, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=17),
 'nvme0n1p3': sdiskio(read_count=4194887, write_count=745270, read_bytes=155737314304, write_bytes=91739934720, read_time=966669, write_time=4210967, read_merged_count=807871, write_merged_count=527722, busy_time=971597),
 'nvme0n1p4': sdiskio(read_count=83, write_count=0, read_bytes=2415616, write_bytes=0, read_time=8, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=24),
 'sda': sdiskio(read_count=3843540, write_count=1732737, read_bytes=64579597312, write_bytes=74396725248, read_time=43589562, write_time=11415495, read_merged_count=1941586, write_merged_count=1536263, busy_time=16041064),
 'sda1': sdiskio(read_count=65, write_count=0, read_bytes=2293760, write_bytes=0, read_time=279, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=294),
 'sda2': sdiskio(read_count=3840553, write_count=1695795, read_bytes=64572838912, write_bytes=74396725248, read_time=43550436, write_time=11078031, read_merged_count=1941579, write_merged_count=1536263, busy_time=15905760),
 'sda3': sdiskio(read_count=85, write_count=0, read_bytes=2408448, write_bytes=0, read_time=611, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=627),
 'sr0': sdiskio(read_count=10, write_count=0, read_bytes=2048, write_bytes=0, read_time=60, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=80)}
$ cat .config/bpytop/error.log
no content
```
