### ISSUE TITLE
[BUG] Crash when started with command-not-found PackageKit wrapper

### ISSUE THREAD

**Issue by ZaWertun** [aristocratos/bpytop#250]
**Describe the bug**

bpytop crashes when started after installation with PackageKit command-not-found wrapper.
I see this error in the console:
```
Traceback (most recent call last):
File "/usr/bin/bpytop", line 5411, in <module>
main()
File "/usr/bin/bpytop", line 5293, in main
Term.echo(False)
File "/usr/bin/bpytop", line 651, in echo
(iflag, oflag, cflag, lflag, ispeed, ospeed, cc) = termios.tcgetattr(sys.stdin.fileno())
termios.error: (25, 'Inappropriate ioctl for device')
```

**To Reproduce**

1. Remove `bpytop` with package manager;
2. Run `/usr/libexec/pk-command-not-found bpytop` and install bpytop again;
3. Crash.

**Expected behavior**

No crash.

**Info (please complete the following information):**
 - bpytop version: 1.0.59
 - psutil version: 5.7.2
 - Linux distribution and version: Fedora 33 x86_64
 - Terminal used: konsole
 - Font used: JetBrains Mono NL
 - Python version: 3.9.1

**Additional context**

```
17/08/20 (00:32:44) | ERROR: Non fatal error during disk io collection!
17/08/20 (00:32:44) | ERROR: Caused by outdated psutil version.
17/08/20 (00:32:44) | ERROR: not sure how to interpret line '   8       0 sda 389 0 14192 243 0 0 0 0 0 252 243 0 0 0 0 0 0\n'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2697, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 389 0 14192 243 0 0 0 0 0 252 243 0 0 0 0 0 0\n'
06/09/20 (19:48:59) | WARNING: psutil version 5.6.7 detected, version 5.7.0 or later required for full functionality!
06/09/20 (19:49:07) | ERROR: Non fatal error during disk io collection!
06/09/20 (19:49:07) | ERROR: Caused by outdated psutil version.
06/09/20 (19:49:07) | ERROR: not sure how to interpret line '   8       0 sda 515 0 14262 426 0 0 0 0 0 518 426 0 0 0 0 0 0\n'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2716, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 515 0 14262 426 0 0 0 0 0 518 426 0 0 0 0 0 0\n'
06/09/20 (19:50:10) | WARNING: psutil version 5.6.7 detected, version 5.7.0 or later required for full functionality!
06/09/20 (19:50:18) | ERROR: Non fatal error during disk io collection!
06/09/20 (19:50:18) | ERROR: Caused by outdated psutil version.
06/09/20 (19:50:18) | ERROR: not sure how to interpret line '   8       0 sda 515 0 14262 426 0 0 0 0 0 518 426 0 0 0 0 0 0\n'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2716, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 515 0 14262 426 0 0 0 0 0 518 426 0 0 0 0 0 0\n'
06/09/20 (19:51:44) | WARNING: psutil version 5.6.7 detected, version 5.7.0 or later required for full functionality!
06/09/20 (19:51:51) | ERROR: Non fatal error during disk io collection!
06/09/20 (19:51:51) | ERROR: Caused by outdated psutil version.
06/09/20 (19:51:51) | ERROR: not sure how to interpret line '   8       0 sda 515 0 14262 426 0 0 0 0 0 518 426 0 0 0 0 0 0\n'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2716, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 515 0 14262 426 0 0 0 0 0 518 426 0 0 0 0 0 0\n'
07/09/20 (15:53:12) | WARNING: psutil version 5.6.7 detected, version 5.7.0 or later required for full functionality!
07/09/20 (15:53:13) | ERROR: Non fatal error during disk io collection!
07/09/20 (15:53:13) | ERROR: Caused by outdated psutil version.
07/09/20 (15:53:13) | ERROR: not sure how to interpret line '   8       0 sda 445 0 14262 309 0 0 0 0 0 352 309 0 0 0 0 0 0\n'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2716, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 445 0 14262 309 0 0 0 0 0 352 309 0 0 0 0 0 0\n'
07/09/20 (15:53:30) | WARNING: psutil version 5.6.7 detected, version 5.7.0 or later required for full functionality!
07/09/20 (15:53:32) | ERROR: Non fatal error during disk io collection!
07/09/20 (15:53:32) | ERROR: Caused by outdated psutil version.
07/09/20 (15:53:32) | ERROR: not sure how to interpret line '   8       0 sda 445 0 14262 309 0 0 0 0 0 352 309 0 0 0 0 0 0\n'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2716, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 445 0 14262 309 0 0 0 0 0 352 309 0 0 0 0 0 0\n'
```

**Comment by aristocratos** [comment]
@ZaWertun 
Report it to the fedora package maintainer at https://src.fedoraproject.org/rpms/bpytop

This is not a `bpytop` bug. 

`termios.error: (25, 'Inappropriate ioctl for device')` is the kind of error you would get when not running in a proper terminal, so my guess would be that "PackageKit command-not-found" is doing something weird when installing.

**Comment by ZaWertun** [comment]
Any other console application works fine under `command-not-found` wrapper, I've tested it.

**Comment by aristocratos** [comment]
@ZaWertun 
That's good and all but there is still nothing for me to do here. BpyTop are never gonna work properly if it can't manipulate the terminal it's running in, which it looks like the `command-not-found` wrapper is stopping it from doing.

**Comment by ZaWertun** [comment]
It can be crashed in bash with this command:
```shell
bpytop <&-
```
According to the documentation `sys.stdin.fileno()` will raise exception if STDIN is closed:
```
fileno()
    Return the underlying file descriptor (an integer) of the stream if it exists. An OSError is raised if the IO object does not use a file descriptor.
```
(https://docs.python.org/3/library/io.html#io.IOBase.fileno)

**Comment by aristocratos** [comment]
@ZaWertun 
Are you suggesting it should ignore the exception if it fails to read `sys.stdin`?
That would not only prevent BpyTop from setting the correct modes but also any user interaction.

The emphasis here should be on making sure a third party tool doesn't prevent STDIN from being accessed, not trying to make BpyTop run normally when being crippled.

**Comment by ZaWertun** [comment]
We need 2 checks here:
1. Don't call `termios.tcgetattr` if `sys.stdin` is `None`, when STDIN is closed;
2. Don't call `termios.tcgetattr` if `sys.stdin` is not tty `sys.stdin.isatty()`, if file has been redirected to STDIN.

**Comment by ZaWertun** [comment]
Or maybe just exit and print some error - it will be more easier.

**Comment by ZaWertun** [comment]
Just checked - don't know why, but when `pk-command-not-found` starts bpytop STDIN is pointing to `/dev/null`.
So better print error and exit, I think.

**Comment by ZaWertun** [comment]
```
diff -r -U3 bpytop-1.0.59.orig/bpytop.py bpytop-1.0.59/bpytop.py
--- bpytop-1.0.59.orig/bpytop.py        2021-01-11 23:53:15.000000000 +0300
+++ bpytop-1.0.59/bpytop.py     2021-01-19 23:15:23.773718634 +0300
@@ -5280,6 +5280,10 @@
THEME: Theme

def main():
+       if sys.stdin is None or not(sys.stdin.isatty()):
+               print("Stdin is closed or not a tty, exiting...")
+               exit(1)
+
global THEME

Term.width = os.get_terminal_size().columns
```
@aristocratos what you say about this check?
