### ISSUE TITLE
[BUG] /proc/diskstats missing causes crash

### ISSUE THREAD

**Issue by jkw** [aristocratos/bpytop#293]
**Describe the bug**

Crashes due to /proc/diskstats not being installed.

**To Reproduce**

Install a fresh Ubuntu Server, install bpytop trough snap.
Run bpytop.
Crashes on permission denied something.

**Expected behavior**

bpytop opening as normal or throwing error missing software.

**Screenshots**

`➜  ~ bpytop
Bpytop exited with errorcode (1). See /home/jkw/snap/bpytop/229/.config/bpytop/error.log for more information!`

**Info (please complete the following information):**
 - bpytop version: 1.0.63
 - psutil version: 5.8.0
 - (Linux) Linux distribution and version: Ubuntu Server 20.10
 - (OSX/FreeBSD) Os release version: -
 - Terminal used: zsh
 - Font used: errr.. Don't know?
 - Python version: 3.8.6

**Additional context**

contents of `~/.config/bpytop/error.log`
`➜  ~ cat snap/bpytop/229/.config/bpytop/error.log
17/04/21 (13:47:23) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
Traceback (most recent call last):
  File "/snap/bpytop/229/usr/bin/bpytop", line 2924, in _runner
    collector._collect()
  File "/snap/bpytop/229/usr/bin/bpytop", line 3318, in _collect
    io_counters = psutil.disk_io_counters(perdisk=SYSTEM != "BSD", nowrap=True)
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/__init__.py", line 2059, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1166, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1117, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_common.py", line 725, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
17/04/21 (13:47:23) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

17/04/21 (14:04:12) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
Traceback (most recent call last):
  File "/snap/bpytop/229/usr/bin/bpytop", line 2924, in _runner
    collector._collect()
  File "/snap/bpytop/229/usr/bin/bpytop", line 3318, in _collect
    io_counters = psutil.disk_io_counters(perdisk=SYSTEM != "BSD", nowrap=True)
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/__init__.py", line 2059, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1166, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1117, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_common.py", line 725, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
17/04/21 (14:04:12) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

17/04/21 (14:07:05) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
Traceback (most recent call last):
  File "/snap/bpytop/229/usr/bin/bpytop", line 2924, in _runner
    collector._collect()
  File "/snap/bpytop/229/usr/bin/bpytop", line 3318, in _collect
    io_counters = psutil.disk_io_counters(perdisk=SYSTEM != "BSD", nowrap=True)
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/__init__.py", line 2059, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1166, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1117, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/229/usr/lib/python3/dist-packages/psutil/_common.py", line 725, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
17/04/21 (14:07:05) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

➜  ~ /proc/diskstats
zsh: permission denied: /proc/diskstats
➜  ~ sudo /proc/diskstats                        
sudo: /proc/diskstats: command not found
➜  ~ `

**Comment by aristocratos** [comment]
Use another installation method or read the complete instructions for the snap install.
See #154
