### ISSUE TITLE
ValueError: 'CPU' is not in list

### ISSUE THREAD

**Issue by NicoWde** [aristocratos/bpytop#3]
Hello there,

I installed bpytop as described. 'psutil' is installed. But it keeps failing with this ValueError.

```
[nico@void ~]$ python --version
Python 3.8.4
[nico@void ~]$ pip --version
pip 20.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)
[nico@void ~]$ lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void
[nico@void ~]$ python3 -m pip install psutil
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psutil in /usr/lib/python3.8/site-packages (5.7.2)
[nico@void ~]$ git clone https://github.com/aristocratos/bpytop.git
Klone nach 'bpytop' ...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 103 (delta 52), reused 77 (delta 29), pack-reused 0
Empfange Objekte: 100% (103/103), 638.70 KiB | 587.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (52/52), Fertig.
[nico@void ~]$ cd bpytop
[nico@void bpytop]$ sudo make install
**[nico@void bpytop]$ bpytop
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 3968, in <module>
    CPU_NAME: str = get_cpu_name()
  File "/usr/local/bin/bpytop", line 3710, in get_cpu_name
    name = nlist[nlist.index("CPU")+1]
ValueError: 'CPU' is not in list**

[nico@void ~]$ bpytop -v
bpytop version: 1.0.0
psutil version: 5.7.2
```

**Comment by NicoWde** [comment]
`[nico@void bpytop]$ bpytop --debug
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 3968, in <module>
    CPU_NAME: str = get_cpu_name()
  File "/usr/local/bin/bpytop", line 3710, in get_cpu_name
    name = nlist[nlist.index("CPU")+1]
ValueError: 'CPU' is not in list`

**Comment by aristocratos** [comment]
That my mistake assuming a Xeon processor would have "CPU" in it's model name :P

Would you mind running `cat /proc/cpuinfo |grep "model name"`

Just curious what the actual model name of you cpu is.

Anyways, will be fixed in v1.0.1 later today.

**Comment by aristocratos** [comment]
Fixed in v1.0.1

**Comment by NicoWde** [comment]
Hey! sorry for my late response..

`[nico@void ~]$ cat /proc/cpuinfo |grep "model name"
model name	: Intel Xeon Processor (Skylake, IBRS)
model name	: Intel Xeon Processor (Skylake, IBRS)
model name	: Intel Xeon Processor (Skylake, IBRS)
model name	: Intel Xeon Processor (Skylake, IBRS)`
