### ISSUE TITLE
[BUG] Crashes when show_disks=False

### ISSUE THREAD

**Issue by remisalmon** [aristocratos/bpytop#31]
**Describe the bug**

Crashes when restarting bpytop with "Show disk" is disabled 

**To Reproduce**

1. `rm -rf ~/.config/bpytop`
2. Start bpytop
3. Set "Show disk" to False
4. Exit bpytop
5. Start bpytop: `Bpytop exited with errorcode (1)`

**Info (please complete the following information):**
 - bpytop version: 1.0.6
 - psutil version: 5.6.7
 - Python version: 3.8.5

**Additional context**

```
Traceback (most recent call last):
  File "Applications/bpytop", line 2630, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line ' 259       0 nvme0n1 71111 19806 3610632 14338 113525 86192 5716165 121101 0 68165 154621 0 0 0 0 5919 19181\n'
06/08/20 (10:34:51) | ERROR: Data collection thread failed with exception: type object 'MemCollector' has no attribute 'disks'
Traceback (most recent call last):
  File "Applications/bpytop", line 2338, in _runner
    collector._draw()
  File "Applications/bpytop", line 2725, in _draw
    MemBox._draw_fg()
  File "Applications/bpytop", line 1672, in _draw_fg
    if len(mem.disks) * 3 <= h + 1:
AttributeError: type object 'MemCollector' has no attribute 'disks'
06/08/20 (10:34:51) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 
```

**Comment by aristocratos** [comment]
Fixed in v1.0.7
