### ISSUE TITLE
[BUG] Instant Crash on M1 MacBook Pro

### ISSUE THREAD

**Issue by impost0r** [aristocratos/bpytop#325]
**Describe the bug**

bpytop fails to run on an M1 MacBook Pro.

**To Reproduce**

Buy an M1 Mac.
`pip3 install --user bpytop`
`bpytop`

**Expected behavior**

bpytop runs, I get to marvel at it.

**Screenshots**

N/A

**Info (please complete the following information):**
- bpytop version: 1.0.67
- psutil version: 5.7.0
- Kernel: Darwin dongforce-arm 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64 (macOS 11.4 (20F71) aarch64)
 - Terminal used: iTerm 2
 - Font used: Monaco
 - Python version: Python 3.7.9

**Additional context**

```
24/06/21 (17:47:32) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/Users/jogn/Library/Python/3.7/lib/python/site-packages/bpytop.py", line 2938, in _runner
    collector._collect()
  File "/Users/jogn/Library/Python/3.7/lib/python/site-packages/bpytop.py", line 3708, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1457, in process_iter
    yield add(pid)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1434, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 538, in as_dict
    ret = meth()
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 690, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python3.7/site-packages/psutil/_psosx.py", line 334, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psutil/_psosx.py", line 418, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
24/06/21 (17:47:32) | WARNING: Exiting with errorcode (1). Runtime 0:00:00
```

Seems to be an error in psutil regarding getting memory info.

**Comment by aristocratos** [comment]
@impost0r 
Your `psutil` version is a bit outdated and I believe there were some patches for M1 Macs in the recent versions.
And you seem to have had `psutil` installed already (likely installed as a privileged user) otherwise you should have gotten the latest version when installing bpytop.
Try updating `psutil` with `python3 -m pip install psutil --upgrade` (with or without sudo).

**Comment by impost0r** [comment]
It's probably that. My headers and such are currently messed up from doing some vuln research so I can't properly install psutil (and this laptop needs to be put on a clean slate anyways). Won't close until I verify it works, but I'll do a fresh reinstall due to Time Machine migrations from x64 Macs to ARM Macs being funky and let you know.
