### ISSUE TITLE
WARNING: Exiting with errorcode (1)[BUG]

### ISSUE THREAD

**Issue by DanimanX** [aristocratos/bpytop#370]
**Describe the bug**

when i excecute bpytop, i've an errorcode (1)

**Expected behavior**

open bpytop 

**Screenshots**

![2021-12-12-115708_800x360_scrot](https://user-images.githubusercontent.com/70829086/145717430-7a606c9c-c48c-469f-9861-bb57be4ed061.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.67
 - psutil version: `5.8.0
 - (Linux) Linux distribution and version: Archlinux
 - (OSX/FreeBSD) Os release version: 5.15.7-zen1-1-zen
 - Terminal used: Alacritty
 - Font used: Iosevka
 - Python version, 3.9.9

**Additional context**

12/12/21 (11:52:05) | ERROR: Data collection thread failed with exception: S
ign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2719, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if pr
og_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if ar
g_len else "") +
ValueError: Sign not allowed in string format specifier

**Config**
color_theme="kyli0x"
theme_background=True
truecolor=True
shown_boxes="cpu mem net proc"
update_ms=2000
proc_update_mult=2
proc_sorting="cpu lazy"
proc_reversed=False
proc_tree=False
tree_depth=3
proc_colors=True
proc_gradient=True
proc_per_core=False
proc_mem_bytes=True
cpu_graph_upper="total"
cpu_graph_lower="total"
cpu_invert_lower=True
cpu_single_graph=False
show_uptime=True
check_temp=True
cpu_sensor=k10temp:Tctl
show_coretemp=True
temp_scale="celsius"
show_cpu_freq=True
draw_clock="%X"
background_update=True
custom_cpu_name=""
disks_filter=""
mem_graphs=True
show_swap=True
swap_disk=True
show_disks=True
only_physical=True
use_fstab=False
show_io_stat=True
io_mode=False
io_graph_combined=False
io_graph_speeds=""
net_download="10M"
net_upload="10M"
net_auto=True
net_sync=False
net_color_fixed=False
net_iface=""
show_battery=True
show_init=False
update_check=True
log_level=WARNING

**Comment by RedStraggler** [comment]
Having the exact same error, any info on a fix for this?
