### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by denisoft81** [aristocratos/bpytop#386]
**Describe the bug**

On terminal the application do not started.

**To Reproduce**

It doesn't happen frequently, it happens randomly.

**Info (please complete the following information):**
 - bpytop version: 1.0.68
 - psutil version: 5.8.0
 - (Linux) Linux distribution and version: Fedora 36
 - Kernel version: 5.17.13-300.fc36.x86_64
 - Terminal used: Tilix 1.9.5
 - Font used: Source Code Pro
 - Python version, 3.10.4

**Additional context**

13/06/22 (17:51:10) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
ValueError: Sign not allowed in string format specifier
13/06/22 (17:51:10) | WARNING: Exiting with errorcode (1). Runtime 0:00:00

**Comment by WaldperlachFabi** [comment]
Same error/problem, on Ubuntu 22.04
