### ISSUE TITLE
[BUG] Crash: 

### ISSUE THREAD

**Issue by jakobbg** [aristocratos/bpytop#55]
```
Bpytop exited with errorcode (1). See /Users/jakobbg/.config/bpytop/error.log for more information!
```

**Expected behavior**

bpytop not crashing

**Info (please complete the following information):**
```
$ ./bpytop.py -v
bpytop version: 1.0.8
psutil version: 5.7.2
```

```
$ uname -a
Darwin bzzzt.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
```

 - Terminal used: iTerm Build 3.4.0beta2

 - Font used: Inconsolata for PowerLine

 - Python version: Python 3.8.5

contents of `~/.config/bpytop/error.log`:

```$ cat /Users/jakobbg/.config/bpytop/error.log
11/08/20 (07:54:14) | ERROR: Data collection thread failed with exception: list index out of range
Traceback (most recent call last):
  File "./bpytop.py", line 2366, in _runner
    collector._draw()
  File "./bpytop.py", line 2562, in _draw
    CpuBox._draw_fg()
  File "./bpytop.py", line 1556, in _draw_fg
    out += (f'{THEME.inactive_fg} ⡀⡀⡀⡀⡀{Mv.l(5)}{THEME.gradient["temp"][cpu.cpu_temp[0][-1]]}{Graphs.temps[0](None if cls.resized else cpu.cpu_temp[0][-1])}'
IndexError: list index out of range
11/08/20 (07:54:16) | WARNING: Exiting with errorcode (1). Runtime 1 day, 0:09:22
```

**Comment by aristocratos** [comment]
Fixed in v1.0.11
