### ISSUE TITLE
[BUG] Crashing

### ISSUE THREAD

**Issue by Wizard28082006** [aristocratos/bpytop#60]
**Describe the bug**

bpytop crashes while starting it up!

**To Reproduce**

Running `bpytop` in terminal crashes it at "Collecting data" stage

**Expected behavior**
bpytop not crashing

**Screenshots**

None

**Info (please complete the following information):**
 - bpytop version: `bpytop version: 1.0.12`
 - psutil version: `psutil version: 5.7.2`
 - (Linux) Linux distribution and version: Pop!_OS 20.04 LTS x86_64
 - (OSX/FreeBSD) Os release version: NA
 - Terminal used: Alacritty
 - Font used: Hack Nerd Font (Patched)
 - Python version, `Python 3.8.5`

**Additional context**
When I first installed bpytop it worked flawlessly, but today it crashes... And when I run the mini version: `bpytop -m` it works fine...

**Error log**
```
12/08/20 (13:39:47) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2367, in _runner
    collector._draw()
  File "/usr/local/bin/bpytop", line 3186, in _draw
    ProcBox._draw_fg()
  File "/usr/local/bin/bpytop", line 2155, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
ValueError: Sign not allowed in string format specifier
12/08/20 (13:39:47) | WARNING: Exiting with errorcode (1). Runtime 0:00:03
```

**Comment by aristocratos** [comment]
You're starting with a terminal smaller than 80x24, currently was a bug that failed to check minimum size at start, will be fixed in next update.

**Comment by aristocratos** [comment]
Fixed in v1.0.13

**Comment by Wizard28082006** [comment]
Cool!
