### ISSUE TITLE
[BUG] Crashes on vanilla Ubuntu 20.04

### ISSUE THREAD

**Issue by phlmike** [aristocratos/bpytop#99]
29/08/20 (12:42:33) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/69/usr/bin/bpytop", line 2398, in _runner
    collector._collect()
  File "/snap/bpytop/69/usr/bin/bpytop", line 2697, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
29/08/20 (12:42:33) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

It was run with sudo.

sudo snap install bpytop
sudo bpytop
**then it crashes**

bpytop version: 1.0.16
psutil version: 5.4.2
Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04
Bash
Python 3.8.2

29/08/20 (12:54:00) | INFO: New instance of bpytop version 1.0.16 started with pid 17323
29/08/20 (12:54:00) | INFO: Loglevel set to DEBUG
29/08/20 (12:54:00) | DEBUG: Using psutil version 5.4.2
29/08/20 (12:54:00) | DEBUG: CMD: /snap/bpytop/69/usr/bin/bpytop --debug
29/08/20 (12:54:00) | INFO: Config file malformatted or missing, will be recreated on exit!
29/08/20 (12:54:01) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/69/usr/bin/bpytop", line 2398, in _runner
    collector._collect()
  File "/snap/bpytop/69/usr/bin/bpytop", line 2697, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/69/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
29/08/20 (12:54:01) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

**Comment by phlmike** [comment]
I just saw the previous one. When installing from snap it doesn't provide that info.
sudo snap connect bpytop:mount-observe

sudo snap connect bpytop:network-control

sudo snap connect bpytop:hardware-observe

sudo snap connect bpytop:system-observe

sudo snap connect bpytop:process-control

sudo snap connect bpytop:physical-memory-observe
